[package]
name = "runir"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-lite = "2.3.0"
uuid = "1.10.0"

[features]
observe = []

[[test]]
name = "test_item_observation"
required-features = ["observe"]