[package]
name = "runir"
description = "Library for building runtime intermediate representations for application objects"
authors = ["juliusl@microsoft.com"]
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
uuid = "1.10.0"
crc = "3.2.1"
